# The main config file for your Jekyll template

# Site settings
# used for the html title of every page
title: Peter Francis
desc: Peter Francis
url: http://rockretep.net
# the subpath of your site, e.g. /blog
baseurl: ''
# how should we display posts url
permalink: /:year/:title/

# Meta settings
email: peter@rockretep.net
author: Peter Francis
twitter_username: rockretep
github_username: rockretep
linkedn_username: peter-francis-042196176

google_analytics:

# Pagination settings
# number of posts to show per page
paginate: 5
# link scheme for articles, should be left as is
paginate_path: "/articles/page:num/"

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Résumé
    url: /assets/francis_peter_resume.pdf
    desc: Peter Francis Résumé
  - title: Portfolio
    url: /portfolio/
    desc: Peter Francis Portfolio
  # - title: Contact
  #   url: /contact/
  #   desc: Peter Francis Contact

collections:
  portfolio:
      output: true
# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: 'portfolio'
    values:
      layout: page

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  # you can change this if you feel like it
  hard_wrap: false
  # allow parsing html inside markdown
  parse_block_html: true

# Build settings
include:
  # all your pages can be put inside pages (except articles)
  - _pages
exclude:
  - README.md
  - vendor
plugins:
  - jekyll-paginate

