about: |
		I'm a student at Indiana University Bloomington pursuing a double-major in Computer Science and Game Design.
    I'm interested in Computer Science, Artificial Intelligence, and Game Development.
    I like to play and make games, experiment programming things, learn about topics in Math and various technology, and hope to develop a better world.
portfolio:
  - 
