# Find all markdown files
MARKDOWN=$(shell find . -iname "*.md")
# Form all 'html' counterparts
HTML=$(MARKDOWN:.md=.html)

# Find all posts markdown files
POSTS=$(shell find . -iwholename "posts/*.md")
# SCSS Files
SCSS=$(shell find . -iwholename "css/*.scss")
CSS=$(SCSS:.scss=.css)
# Prefix directory
PREFIX := _site/

# Default template
DEFAULTTEMPLATE := templates/default.template
# Post template
POSTTEMPLATE := templates/post.template

.PHONY = all tar clean

all:
	mkdir -p _site/

index.html: index.md
	pandoc --from markdown_mmd --to html --template $(DEFAULTTEMPLATE)

%.html: $(POSTS)
	pandoc --from markdown_mmd --to html --template $(POSTTEMPLATE) --output=$(DESTDIR)$(PREFIX)/posts/$@

%.css: $(SCSS)
	sassc $@ $(OUTPUT)/css/$@

tar: $(MARKDOWN)
	tar --exclude=notes.tar.gz --exclude=.git/ -czvf notes.tar.gz ./

clean:
	rm -rf $(DESTDIR)$(PREFIX)
