posts:
  - rift_rally:
    filename: rift_rally
    title: Rift Rally
    subtitle: 
    date: 2020-05-01
    tags: [Company, Team, Game, C, C++, Scripting, Computer-Vision, Shaders, UI]
    confidence: Certain
    mainimage: riftrally1.png
  - oddestsea:
    filename: oddestsea
    title: OddestSea
    subtitle: Published, team developed indie game about sailing in a dark, eerie sea
    date: 2020-05-01
    tags: [Team, Game, Unity, C#, Scripting, Design, AI, Shaders]
    confidence: Certain
    mainimage: oddestsea2.png
  - AI_framework:
    filename: AI_framework
    title: AI Framework for games
    subtitle: Small, general-purpose AI framework
    date: 2020
    tags: [Solo, Tool, C, AI]
    confidence: Unlikely
    mainimage: bubo.png
  - asymars:
    filename: asymars
    title: Asymars
    subtitle: AI project and original game based on chess
    date: 2018-05-05
    tags: [Team, Game, Unity, C#, Scripting, AI]
    confidence: Certain
    mainimage: asymars2.png
  - banished_parser:
    filename: banished_parser
    title: Banished Parser
    subtitle: OCR tool to parse and record data from the game *Banished*
    date: 2019-09-01
    tags: [Solo, Tool, JS, AI]
    confidence: Certain
    mainimage: banished2.png
  #- brainfreeze:
  #  filename: brainfreeze
  #  title: Brain Freeze
  #  subtitle: Early venture into using game engines.
  #  date: 2014-12-01
  #  tags: [Solo, Game, GameMaker, Scripting, Design]
  #  confidence: Unlikely
  #  mainimage: brainfreeze1.png
  - charbble:
    filename: charbble
    title: Charbble
    subtitle: Rouge-like puzzle game influenced by *Scrabble* and crosswords
    date: 2017-12-14
    tags: [Solo, Game, Unity, C#, Scripting, Design]
    confidence: Likely
    mainimage: charbble1.png
  - taps:
    filename: taps
    title: The Astro Parcel Service
    subtitle: Development for *The Astro Parcel Service* (TAPS)
    date: 2020-05-01
    tags: [Team, Game, Unity, C#, Scripting, AI]
    confidence: Certain
    mainimage: taps1.png
  - tumble_blocks:
    filename: tumble_blocks
    title: Tumble Blocks
    subtitle: Spatial puzzle game with tumbling blocks
    date: 2018-06-01
    tags: [Team, Game, Unity, C#, Scripting, Math, Design]
    confidence: Possible
    mainimage: tumbleblock3.png
